#!/usr/bin/env bash

# switch-transport.sh - Switch between MCP transport modes
# For HTTP transport: logs appear directly in this terminal

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

# Get script directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIG_FILE="$SCRIPT_DIR/.mcp_transport_config"
ENV_FILE="$SCRIPT_DIR/.env"

# Print functions
print_header() {
    echo ""
    echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo -e "${BLUE}$1${NC}"
    echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo ""
}

print_success() {
    echo -e "${GREEN}✓${NC} $1"
}

print_error() {
    echo -e "${RED}✗${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}⚠${NC} $1"
}

print_info() {
    echo -e "${BLUE}ℹ${NC} $1"
}

# Prompt user for configuration
prompt_for_config() {
    print_header "Elasticsearch Configuration Setup"

    echo "Please provide your Elasticsearch connection details."
    echo "Press Enter to accept the default value shown in brackets."
    echo ""

    # Elasticsearch Host
    read -p "Elasticsearch Host [http://localhost:9200]: " input_host
    ELASTICSEARCH_HOSTS="${input_host:-http://localhost:9200}"

    # Authentication method
    echo ""
    echo "Authentication method:"
    echo "  1) Username/Password (most common)"
    echo "  2) API Key"
    read -p "Select [1]: " auth_method
    auth_method="${auth_method:-1}"

    if [ "$auth_method" = "2" ]; then
        read -p "API Key: " ELASTICSEARCH_API_KEY
        ELASTICSEARCH_USERNAME=""
        ELASTICSEARCH_PASSWORD=""
    else
        read -p "Username [elastic]: " input_user
        ELASTICSEARCH_USERNAME="${input_user:-elastic}"
        read -s -p "Password: " ELASTICSEARCH_PASSWORD
        echo ""  # New line after hidden password input
        ELASTICSEARCH_API_KEY=""
    fi

    # SSL verification
    echo ""
    read -p "Verify SSL certificates? (y/n) [n]: " verify_ssl
    if [ "${verify_ssl,,}" = "y" ] || [ "${verify_ssl,,}" = "yes" ]; then
        VERIFY_CERTS="true"
    else
        VERIFY_CERTS="false"
    fi

    # High-risk operations
    read -p "Disable high-risk write operations? (recommended for IR) (y/n) [y]: " disable_risk
    if [ "${disable_risk,,}" = "n" ] || [ "${disable_risk,,}" = "no" ]; then
        DISABLE_HIGH_RISK_OPERATIONS="false"
    else
        DISABLE_HIGH_RISK_OPERATIONS="true"
    fi

    # MCP Server bind address (for HTTP transport)
    echo ""
    echo "MCP Server Configuration (for HTTP transport):"
    echo "  - Use 127.0.0.1 for local access only"
    echo "  - Use 0.0.0.0 to allow remote connections"
    read -p "MCP Server bind address [0.0.0.0]: " input_mcp_host
    MCP_SERVER_HOST="${input_mcp_host:-0.0.0.0}"

    read -p "MCP Server port [8000]: " input_mcp_port
    MCP_SERVER_PORT="${input_mcp_port:-8000}"

    # Export for current session
    export ELASTICSEARCH_HOSTS
    export ELASTICSEARCH_USERNAME
    export ELASTICSEARCH_PASSWORD
    export ELASTICSEARCH_API_KEY
    export VERIFY_CERTS
    export DISABLE_HIGH_RISK_OPERATIONS
    export MCP_SERVER_HOST
    export MCP_SERVER_PORT

    # Save to .env file
    echo ""
    read -p "Save configuration to .env file? (y/n) [y]: " save_config
    if [ "${save_config,,}" != "n" ] && [ "${save_config,,}" != "no" ]; then
        save_env_file
        print_success "Configuration saved to .env"
    fi

    echo ""
    print_success "Configuration complete"
}

# Save configuration to .env file
save_env_file() {
    cat > "$ENV_FILE" << EOF
# ============================================================
# Elasticsearch Connection Configuration
# Generated by switch-transport.sh on $(date)
# ============================================================

ELASTICSEARCH_HOSTS=${ELASTICSEARCH_HOSTS}
EOF

    if [ -n "$ELASTICSEARCH_API_KEY" ]; then
        echo "ELASTICSEARCH_API_KEY=${ELASTICSEARCH_API_KEY}" >> "$ENV_FILE"
    else
        echo "ELASTICSEARCH_USERNAME=${ELASTICSEARCH_USERNAME}" >> "$ENV_FILE"
        echo "ELASTICSEARCH_PASSWORD=${ELASTICSEARCH_PASSWORD}" >> "$ENV_FILE"
    fi

    cat >> "$ENV_FILE" << EOF
VERIFY_CERTS=${VERIFY_CERTS}
DISABLE_HIGH_RISK_OPERATIONS=${DISABLE_HIGH_RISK_OPERATIONS}

# ============================================================
# MCP Server Configuration (for HTTP transport)
# ============================================================
MCP_SERVER_HOST=${MCP_SERVER_HOST:-0.0.0.0}
MCP_SERVER_PORT=${MCP_SERVER_PORT:-8000}
EOF

    chmod 600 "$ENV_FILE"  # Restrict permissions for security
}

# Test Elasticsearch connection
test_connection() {
    print_info "Testing Elasticsearch connection..."

    local curl_opts="-s --connect-timeout 5"
    if [ "$VERIFY_CERTS" = "false" ]; then
        curl_opts="$curl_opts -k"
    fi

    local auth_header=""
    if [ -n "$ELASTICSEARCH_API_KEY" ]; then
        auth_header="-H \"Authorization: ApiKey ${ELASTICSEARCH_API_KEY}\""
    elif [ -n "$ELASTICSEARCH_USERNAME" ] && [ -n "$ELASTICSEARCH_PASSWORD" ]; then
        auth_header="-u \"${ELASTICSEARCH_USERNAME}:${ELASTICSEARCH_PASSWORD}\""
    fi

    local response
    response=$(eval curl $curl_opts $auth_header "${ELASTICSEARCH_HOSTS}" 2>&1)

    if echo "$response" | grep -q "cluster_name"; then
        local cluster_name=$(echo "$response" | grep -o '"cluster_name" *: *"[^"]*"' | sed 's/.*: *"\([^"]*\)"/\1/')
        print_success "Connected to Elasticsearch cluster: $cluster_name"
        return 0
    else
        print_error "Failed to connect to Elasticsearch"
        print_warning "Response: $(echo "$response" | head -c 200)"
        return 1
    fi
}

# Test MCP server health (HTTP mode)
test_mcp_health() {
    local host="${1:-${MCP_SERVER_HOST:-127.0.0.1}}"
    local port="${2:-${MCP_SERVER_PORT:-8000}}"
    local max_attempts="${3:-10}"
    local attempt=1

    print_info "Waiting for MCP server to be ready..."

    while [ $attempt -le $max_attempts ]; do
        # Try to connect to the MCP endpoint with proper headers for streamable-http
        local response
        response=$(curl -s --connect-timeout 2 "http://${host}:${port}/mcp/" \
            -H "Content-Type: application/json" \
            -H "Accept: application/json, text/event-stream" \
            -d '{"jsonrpc":"2.0","method":"initialize","params":{"protocolVersion":"2024-11-05","capabilities":{},"clientInfo":{"name":"healthcheck","version":"1.0"}},"id":1}' 2>&1)

        # Check for successful MCP response (serverInfo in response means success)
        if echo "$response" | grep -q "serverInfo\|protocolVersion\|result"; then
            print_success "MCP server is healthy and responding"
            return 0
        fi

        # Check for JSON-RPC error response (server is running but returned error)
        if echo "$response" | grep -q '"jsonrpc"'; then
            print_success "MCP server is responding on ${host}:${port}"
            return 0
        fi

        # Also check if server is at least listening
        if nc -z "$host" "$port" 2>/dev/null; then
            if [ $attempt -eq $max_attempts ]; then
                print_success "MCP server is listening on ${host}:${port}"
                return 0
            fi
        fi

        echo -n "."
        sleep 1
        attempt=$((attempt + 1))
    done

    echo ""
    print_warning "MCP server health check timed out after ${max_attempts} seconds"
    print_info "Server may still be starting up..."
    return 1
}

# Load environment variables
load_env() {
    # First, try loading from .env file
    if [ -f "$ENV_FILE" ]; then
        set -a
        source "$ENV_FILE"
        set +a
        print_success "Loaded configuration from .env"
        return 0
    fi

    # Try loading from config file (legacy)
    if [ -f "$CONFIG_FILE" ]; then
        source "$CONFIG_FILE"
        export ELASTICSEARCH_HOSTS="${ES_HOST:-$ELASTICSEARCH_HOSTS}"
        export ELASTICSEARCH_USERNAME="${ES_USERNAME:-$ELASTICSEARCH_USERNAME}"
        export ELASTICSEARCH_PASSWORD="${ES_PASSWORD:-$ELASTICSEARCH_PASSWORD}"
        export ELASTICSEARCH_API_KEY="${ES_API_KEY:-$ELASTICSEARCH_API_KEY}"
        export VERIFY_CERTS="${VERIFY_CERTS:-false}"
        export DISABLE_HIGH_RISK_OPERATIONS="${DISABLE_HIGH_RISK:-true}"
        print_success "Loaded configuration from legacy config file"
        return 0
    fi

    # No configuration found - prompt user
    print_warning "No configuration found"
    echo ""
    read -p "Would you like to configure Elasticsearch connection now? (y/n) [y]: " do_setup

    if [ "${do_setup,,}" = "n" ] || [ "${do_setup,,}" = "no" ]; then
        print_error "Configuration required. Please create a .env file or run this script again."
        echo ""
        echo "Required environment variables:"
        echo "  ELASTICSEARCH_HOSTS=https://localhost:9200"
        echo "  ELASTICSEARCH_USERNAME=elastic"
        echo "  ELASTICSEARCH_PASSWORD=yourpassword"
        echo "  VERIFY_CERTS=false"
        exit 1
    fi

    prompt_for_config
}

# Kill process on port
kill_port() {
    local port=$1
    local pid=$(lsof -ti:$port 2>/dev/null || true)

    if [ -n "$pid" ]; then
        print_warning "Port $port is in use (PID: $pid), killing..."
        kill -9 $pid 2>/dev/null || true
        sleep 1
        print_success "Port $port freed"
    fi
}

# Configure Claude Code for stdio transport
configure_stdio() {
    print_header "Configuring Claude Code for stdio Transport"

    # Remove existing configuration
    claude mcp remove crowdsentinel 2>/dev/null || true

    # Add with stdio (Claude Code spawns the server)
    local cmd="claude mcp add crowdsentinel"
    cmd="$cmd --env ELASTICSEARCH_HOSTS=\"${ELASTICSEARCH_HOSTS}\""

    if [ -n "$ELASTICSEARCH_USERNAME" ]; then
        cmd="$cmd --env ELASTICSEARCH_USERNAME=\"${ELASTICSEARCH_USERNAME}\""
    fi
    if [ -n "$ELASTICSEARCH_PASSWORD" ]; then
        cmd="$cmd --env ELASTICSEARCH_PASSWORD=\"${ELASTICSEARCH_PASSWORD}\""
    fi
    if [ -n "$ELASTICSEARCH_API_KEY" ]; then
        cmd="$cmd --env ELASTICSEARCH_API_KEY=\"${ELASTICSEARCH_API_KEY}\""
    fi

    cmd="$cmd --env VERIFY_CERTS=\"${VERIFY_CERTS:-false}\""
    cmd="$cmd --env DISABLE_HIGH_RISK_OPERATIONS=\"${DISABLE_HIGH_RISK_OPERATIONS:-true}\""
    cmd="$cmd -- uv --directory \"$SCRIPT_DIR\" run crowdsentinel-mcp-server"

    eval "$cmd"

    if [ $? -eq 0 ]; then
        print_success "Claude Code configured for stdio transport"
        echo ""
        print_info "Logs will be written to: /tmp/crowdsentinel/mcp-server.log"
        print_info "View logs: tail -f /tmp/crowdsentinel/mcp-server.log"
    else
        print_error "Failed to configure Claude Code"
        exit 1
    fi
}

# Configure Claude Code for HTTP transport (URL only)
configure_http() {
    local host="${1:-${MCP_SERVER_HOST:-0.0.0.0}}"
    local port="${2:-${MCP_SERVER_PORT:-8000}}"
    local transport="${3:-streamable-http}"
    # Use trailing slash to match server path and avoid 307 redirects
    local endpoint_path="mcp/"
    local claude_transport="http"

    if [ "$transport" = "sse" ]; then
        endpoint_path="sse/"
        claude_transport="sse"
    fi

    # For Claude Code URL, use the appropriate host
    # If binding to 0.0.0.0, Claude connects via 127.0.0.1
    local connect_host="$host"
    if [ "$host" = "0.0.0.0" ]; then
        connect_host="127.0.0.1"
    fi

    local url="http://${connect_host}:${port}/${endpoint_path}"

    print_header "Configuring Claude Code for HTTP Transport"

    # Remove existing configuration
    claude mcp remove crowdsentinel 2>/dev/null || true

    # Add with URL (server runs separately)
    # Format: claude mcp add --transport http name url
    claude mcp add --transport "$claude_transport" crowdsentinel "$url"

    if [ $? -eq 0 ]; then
        print_success "Claude Code configured to connect to $url"
        print_info "Server will bind to ${host}:${port}"
    else
        print_error "Failed to configure Claude Code"
        exit 1
    fi
}

# Run server in foreground (for HTTP transport)
run_http_server() {
    local host="${1:-${MCP_SERVER_HOST:-0.0.0.0}}"
    local port="${2:-${MCP_SERVER_PORT:-8000}}"
    local transport="${3:-streamable-http}"

    print_header "Starting MCP Server (HTTP Transport)"

    # Kill any existing process on the port
    kill_port "$port"

    echo ""
    print_success "Server binding to ${host}:${port}"
    print_success "Transport: $transport"
    print_info "Logs will appear below in real-time"
    print_info "Press Ctrl+C to stop the server"

    # Show connection info
    echo ""
    if [ "$host" = "0.0.0.0" ]; then
        print_info "Local access: http://127.0.0.1:${port}/mcp"
        local ip_addr=$(hostname -I 2>/dev/null | awk '{print $1}')
        if [ -n "$ip_addr" ]; then
            print_info "Remote access: http://${ip_addr}:${port}/mcp"
        fi
    else
        print_info "Access URL: http://${host}:${port}/mcp"
    fi

    echo ""
    echo -e "${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo -e "${CYAN}                    SERVER LOGS                        ${NC}"
    echo -e "${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo ""

    # Run server in foreground - logs appear directly in terminal
    exec uv --directory "$SCRIPT_DIR" run crowdsentinel-mcp-server \
        --transport "$transport" \
        --host "$host" \
        --port "$port"
}

# Show usage
show_usage() {
    echo "Usage: $0 [command]"
    echo ""
    echo -e "${CYAN}Configuration Commands:${NC}"
    echo "  setup              Configure Elasticsearch connection (interactive)"
    echo "  test               Test Elasticsearch connection"
    echo "  status             Show current configuration and server status"
    echo ""
    echo -e "${CYAN}Transport Commands:${NC}"
    echo "  stdio              Switch to stdio transport (default for Claude Code)"
    echo "  http [port]        Switch to HTTP transport and run server (default port: 8000)"
    echo "  sse [port]         Switch to SSE transport and run server (default port: 8000)"
    echo "  logs               Tail the log file (for stdio transport)"
    echo ""
    echo -e "${CYAN}Examples:${NC}"
    echo "  $0 setup           # Configure Elasticsearch connection interactively"
    echo "  $0 test            # Verify Elasticsearch connection works"
    echo "  $0 stdio           # Configure for stdio, logs go to file"
    echo "  $0 http            # Run HTTP server on port 8000, logs in terminal"
    echo "  $0 http 9000       # Run HTTP server on port 9000"
    echo "  $0 logs            # Watch stdio logs in real-time"
    echo ""
    echo -e "${CYAN}For HTTP/SSE transport:${NC}"
    echo "  1. Run '$0 http' in this terminal (keeps running, shows logs)"
    echo "  2. Use Claude Code in another terminal"
    echo "  3. Tool calls will appear here in real-time"
    echo ""
    echo -e "${CYAN}First-time Setup:${NC}"
    echo "  1. Run '$0 setup' to configure Elasticsearch connection"
    echo "  2. Run '$0 test' to verify the connection works"
    echo "  3. Run '$0 stdio' or '$0 http' to start using the server"
}

# Show status
show_status() {
    print_header "Current Configuration"

    # Show Elasticsearch configuration
    echo -e "${CYAN}Elasticsearch Configuration:${NC}"
    if [ -f "$ENV_FILE" ]; then
        # Load config to display
        set -a
        source "$ENV_FILE"
        set +a
        echo "  Host: ${ELASTICSEARCH_HOSTS:-not set}"
        if [ -n "$ELASTICSEARCH_API_KEY" ]; then
            echo "  Auth: API Key (${ELASTICSEARCH_API_KEY:0:8}...)"
        elif [ -n "$ELASTICSEARCH_USERNAME" ]; then
            echo "  Auth: Username/Password (user: $ELASTICSEARCH_USERNAME)"
        else
            echo "  Auth: Not configured"
        fi
        echo "  Verify Certs: ${VERIFY_CERTS:-false}"
        echo "  High-Risk Ops Disabled: ${DISABLE_HIGH_RISK_OPERATIONS:-true}"
        echo "  Config File: $ENV_FILE"
        echo ""
        echo -e "${CYAN}MCP Server Configuration:${NC}"
        echo "  Bind Address: ${MCP_SERVER_HOST:-0.0.0.0}"
        echo "  Port: ${MCP_SERVER_PORT:-8000}"
    else
        echo "  No configuration found. Run '$0 setup' to configure."
    fi

    echo ""
    echo -e "${CYAN}Claude Code MCP Configuration:${NC}"
    claude mcp list 2>/dev/null | grep -A5 crowdsentinel || echo "  Not configured"
    echo ""

    # Check if server is running
    echo -e "${CYAN}Server Status:${NC}"
    local http_pid=$(lsof -ti:8000 2>/dev/null || true)
    if [ -n "$http_pid" ]; then
        echo "  HTTP server running on port 8000 (PID: $http_pid)"
    else
        echo "  No HTTP server running"
    fi

    # Check log file
    echo ""
    echo -e "${CYAN}Log File:${NC}"
    if [ -f "/tmp/crowdsentinel/mcp-server.log" ]; then
        echo "  /tmp/crowdsentinel/mcp-server.log ($(wc -l < /tmp/crowdsentinel/mcp-server.log) lines)"
        echo "  Last entry: $(tail -1 /tmp/crowdsentinel/mcp-server.log 2>/dev/null || echo 'empty')"
    else
        echo "  No log file yet"
    fi

    # Test connection if configured
    if [ -f "$ENV_FILE" ]; then
        echo ""
        echo -e "${CYAN}Connection Test:${NC}"
        test_connection
    fi
}

# Tail logs
tail_logs() {
    local log_file="/tmp/crowdsentinel/mcp-server.log"

    if [ ! -f "$log_file" ]; then
        print_warning "Log file not found: $log_file"
        print_info "Start the server first, then logs will appear here"
        # Create directory and wait for file
        mkdir -p /tmp/crowdsentinel
        touch "$log_file"
    fi

    print_header "Watching MCP Server Logs"
    print_info "Log file: $log_file"
    print_info "Press Ctrl+C to stop"
    echo ""

    tail -f "$log_file"
}

# Main
main() {
    local command="${1:-}"
    local port_override="${2:-}"

    case "$command" in
        setup|configure)
            prompt_for_config
            echo ""
            read -p "Would you like to test the connection now? (y/n) [y]: " do_test
            if [ "${do_test,,}" != "n" ] && [ "${do_test,,}" != "no" ]; then
                echo ""
                test_connection
            fi
            ;;
        test|verify)
            load_env
            test_connection
            ;;
        stdio)
            load_env
            test_connection || {
                print_error "Cannot start server - Elasticsearch connection failed"
                exit 1
            }
            configure_stdio
            echo ""
            print_header "Setup Complete"
            echo "To view logs while using Claude Code:"
            echo "  tail -f /tmp/crowdsentinel/mcp-server.log"
            echo ""
            echo "Or run in another terminal:"
            echo "  $0 logs"
            ;;
        http|streamable-http)
            load_env
            test_connection || {
                print_error "Cannot start server - Elasticsearch connection failed"
                exit 1
            }
            # Use command-line port if provided, otherwise use env config
            local host="${MCP_SERVER_HOST:-0.0.0.0}"
            local port="${port_override:-${MCP_SERVER_PORT:-8000}}"
            configure_http "$host" "$port" "streamable-http"
            # Run health check in background after server starts
            (sleep 2 && test_mcp_health "127.0.0.1" "$port" 5) &
            run_http_server "$host" "$port" "streamable-http"
            ;;
        sse)
            load_env
            test_connection || {
                print_error "Cannot start server - Elasticsearch connection failed"
                exit 1
            }
            # Use command-line port if provided, otherwise use env config
            local host="${MCP_SERVER_HOST:-0.0.0.0}"
            local port="${port_override:-${MCP_SERVER_PORT:-8000}}"
            configure_http "$host" "$port" "sse"
            # Run health check in background after server starts
            (sleep 2 && test_mcp_health "127.0.0.1" "$port" 5) &
            run_http_server "$host" "$port" "sse"
            ;;
        status)
            show_status
            ;;
        logs)
            tail_logs
            ;;
        -h|--help|help)
            show_usage
            ;;
        "")
            show_usage
            ;;
        *)
            print_error "Unknown command: $command"
            echo ""
            show_usage
            exit 1
            ;;
    esac
}

main "$@"
